### ISSUE TITLE
[Question] Use in monorepos

### ISSUE THREAD

**Issue by lonix1** [HardikModha/vscode-create-tests#9]
Suppose my monorepo has this structure

- root
  - packages
    - lib1
      - src
        - foo
          - bar
            - baz.ts
            - qux.ts
      - test
    - lib2
      - src
      - test
    - lib3
      - src
      - test

So `baz.ts` should have a test file created in the path:
`root/packages/lib1/test/foo/bar/baz.test.ts`

However the test file is actually created in this path:
`root/test/packages/lib1/foo/bar/baz.test.ts`.

Is there a config option to specify this? Keep in mind it's a monorepo so I can't hardcode the location. Ideally the extension should walk up the tree.

**Comment by hardikmodha** [comment]
Hi, Sorry for getting back late. I don't know how I missed it.
> However the test file is actually created in this path:
root/test/packages/lib1/foo/bar/baz.test.ts

I doubt this is because of the configuration issue. Can you please verify that
`createTests.defaultLocationForTestFiles` is set to `same location as source file`?

> Keep in mind it's a monorepo so I can't hardcode the location. 

Yes, You will not need to hardcode the exact location. 

> Ideally the extension should walk up the tree.

Currently, it's not doing that way. It's a very basic version of the extension. I plan to add some enhancements but I'm evaluating some better options.
